'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirUnRar() As String
            Get
                Return CType(Me("dirUnRar"),String)
            End Get
            Set
                Me("dirUnRar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirComTor() As String
            Get
                Return CType(Me("dirComTor"),String)
            End Get
            Set
                Me("dirComTor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirMovDl() As String
            Get
                Return CType(Me("dirMovDl"),String)
            End Get
            Set
                Me("dirMovDl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirMovExt() As String
            Get
                Return CType(Me("dirMovExt"),String)
            End Get
            Set
                Me("dirMovExt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirTVDl() As String
            Get
                Return CType(Me("dirTVDl"),String)
            End Get
            Set
                Me("dirTVDl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*.torrent")>  _
        Public Property ext() As String
            Get
                Return CType(Me("ext"),String)
            End Get
            Set
                Me("ext") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirTVExt() As String
            Get
                Return CType(Me("dirTVExt"),String)
            End Get
            Set
                Me("dirTVExt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NotifyYorN() As Boolean
            Get
                Return CType(Me("NotifyYorN"),Boolean)
            End Get
            Set
                Me("NotifyYorN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoStart() As Boolean
            Get
                Return CType(Me("AutoStart"),Boolean)
            End Get
            Set
                Me("AutoStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property GroupToggle() As Boolean
            Get
                Return CType(Me("GroupToggle"),Boolean)
            End Get
            Set
                Me("GroupToggle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSName() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSName"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSDesc() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSDesc"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSDesc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSDate() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSDate"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSTime() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSTime"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSGroup() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSGroup"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSGroup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSMade() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSMade"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSMade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("s#?*e#?")>  _
        Public Property Filters() As String
            Get
                Return CType(Me("Filters"),String)
            End Get
            Set
                Me("Filters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Double Click to set directory")>  _
        Public Property dirTVUnSor() As String
            Get
                Return CType(Me("dirTVUnSor"),String)
            End Get
            Set
                Me("dirTVUnSor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WinStartUp() As Boolean
            Get
                Return CType(Me("WinStartUp"),Boolean)
            End Get
            Set
                Me("WinStartUp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartupMin() As Boolean
            Get
                Return CType(Me("StartupMin"),Boolean)
            End Get
            Set
                Me("StartupMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TS, CAM, AC3, xvid, DVDSCR, DVDR, DVDRip, BDRip, PROPER, HDTV, PDTV, [REQ], PAL, "& _ 
            "NTSC")>  _
        Public Property RenamingFilters() As String
            Get
                Return CType(Me("RenamingFilters"),String)
            End Get
            Set
                Me("RenamingFilters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{Name} {Year} - {HD}")>  _
        Public Property MovieNaming() As String
            Get
                Return CType(Me("MovieNaming"),String)
            End Get
            Set
                Me("MovieNaming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{Name} - {Season} - {Episode} - {Title} - {HD}")>  _
        Public Property TVNaming() As String
            Get
                Return CType(Me("TVNaming"),String)
            End Get
            Set
                Me("TVNaming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50000")>  _
        Public Property FileIgnoreSize() As String
            Get
                Return CType(Me("FileIgnoreSize"),String)
            End Get
            Set
                Me("FileIgnoreSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".mkv .m4v .avi .mp4 .flv")>  _
        Public Property FileExtensions() As String
            Get
                Return CType(Me("FileExtensions"),String)
            End Get
            Set
                Me("FileExtensions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OverRide() As Boolean
            Get
                Return CType(Me("OverRide"),Boolean)
            End Get
            Set
                Me("OverRide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property MaxRename() As String
            Get
                Return CType(Me("MaxRename"),String)
            End Get
            Set
                Me("MaxRename") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ProcessAllTors() As Boolean
            Get
                Return CType(Me("ProcessAllTors"),Boolean)
            End Get
            Set
                Me("ProcessAllTors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("496, 206")>  _
        Public Property FormSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("FormSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("FormSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("153:112:73:75:79:0:0")>  _
        Public Property ColumnSizes() As String
            Get
                Return CType(Me("ColumnSizes"),String)
            End Get
            Set
                Me("ColumnSizes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LVSPath() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LVSPath"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LVSPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CleanUp() As Boolean
            Get
                Return CType(Me("CleanUp"),Boolean)
            End Get
            Set
                Me("CleanUp") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TorrentAutoExtractor.My.MySettings
            Get
                Return Global.TorrentAutoExtractor.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
